FROM node@sha256:f9ab18e354e6855ae56ef2b290dd225c1e51a564f87584b9bd21dd651838830e

LABEL org.opencontainers.image.title="base-image-vuln-test" \
      org.opencontainers.image.version="1.0.0" \
      org.opencontainers.image.descriion="Test image with a critical vulnerability inherited purely from the public base image" \
      org.opencontainers.image.source="https://github.com/LucasChevrierGit/test-docker-file-remediation" \
      com.datadoghq.image.source_path="newcase-remediated_copy_no_commit/Dockerfile"

CMD ["/bin/bash"]
